### ISSUE TITLE
Ionic 3 : geolocation.watchPosition not getting fired in some Android version 9 devices?

### ISSUE THREAD

**Issue by kapilSoni101** [apache/cordova-plugin-geolocation#175]
Hi team,

I have implemented tracking functionality in ionic3 app its working perfectly in all android version below 9 but in some android 9 version devices its not working.

So lets start,after testing my App on four real devices, I distinguished three different behaviors:

Android 7.1.x (Redmi MI 4A) => working Correctly

Android 9 => I checked in 2 different devices both are android 9 version 1st "Nokia 6" in which watchPosition fired properly but in the other device - Oppo F11 -pro watchPosition function didn't fire.

         self.map = new google.maps.Map(self.mapElement.nativeElement, mapOptions);  

         //get user currentLocation and update user location after move move    
         self.watch = self.geolocation.watchPosition();
         self.subscription = self.watch.subscribe((position) => {
          var latLng = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);

          console.log('lat fire1.....', +position.coords.latitude);
          console.log('long fire.....', +position.coords.longitude);
          //set center to map and set zoom....
          self.map.setCenter(latLng);
          self.map.setZoom(16);
        }, (err) => {
            console.log(err);
        });
      });
    }
 have tried everything but nothing worked for me. Please check my code and tell me what is wrong in my code?

I used below version:

Cordova:7.0.0 Android:- 6.4.0

**Comment by breautek** [comment]
Please read my [gist](https://gist.github.com/breautek/d6231fa33d6942c269296546892afb5e) on why you may not be receiving GPS points as expected. 

Most of the time this is a combination of the phone not configured to use AGPS (so it relies soley on GPS satellites) & the device being in a poor  environment such as in a large buildings or basements.

**Comment by breautek** [comment]
If there are no response over the next couple of days or so then I'm going to assume this issue has been resolved and I'll close the ticket.

**Comment by kapilSoni101** [comment]
@breautek:- no sir actually I am working on another project that the reason not give me reply but sir my issue is not resolved tell what I do for fix ?

**Comment by breautek** [comment]
Ok no problem! There's a lot of what appears to be abandoned tickets here that I'm just trying to clean up, hence why I'm giving a warning before I close any of them.

> @breautek:- no sir actually I am working on another project that the reason not give me reply but sir my issue is not resolved tell what I do for fix ?

Most of the time inaccurate or lack of GPS points being received is cause by the environment, or the phone settings, or both. For the phone settings, using the High accuracy option (not to be confused with the `highAccuracy` option in the geolocation API) and enabling using bluetooth & wifi will assist the GPS in the phone to receive gps points faster.

If you're in a tall building such as an office building or in a basement, these kind of environments can also hinder the ability to receive GPS. GPS in android devices are not standardised so each android phone can experience different behaviour and some phones may work better than other phones in certain environments.

My gist located at https://gist.github.com/breautek/d6231fa33d6942c269296546892afb5e goes into some more detail on this.

**Comment by kapilSoni101** [comment]
Sir I tried both getCurrentPosition and watch position function but both are not fired in oppo device but in another devices it's fire.
Yes sir I agree with you if I am in office building or in a basement, these kind of environment I got different behavior of GPS I have already set highAccuracy but not accurate location.
Sir I will try to upgrade the latest versions and let u know.thanks for ur valuable response sir.

**Comment by aredsterz** [comment]
Hi @kapilSoni101 , I found that  some device especially android 9  not support for webview  navigator.geolocation. (return not found module navigator.geolocation). 
`var geo = cordova.require('cordova/modulemapper').getOriginalSymbol(window, 'navigator.geolocation');`
So, you can try this plugin:
https://www.npmjs.com/package/cordova-plugin-locationservices
This plugin using google play service location.

**Comment by breautek** [comment]
Closing due to lack of response.

**Comment by kapilSoni101** [comment]
@breautek: sorry sir for my late response.i have tried above plugin sir it's working in Android 9 but now problem is that suppose if I am stop in any signal watch Position function stop firing.its working if kill then app then launch again.
Can u tell me what the problem?

**Comment by timbru31** [comment]
Please open a new issue for a new problem and make sure to follow the issue template, thanks!

**Comment by breautek** [comment]
If you have a problem with https://www.npmjs.com/package/cordova-plugin-locationservices plugin, then you'll have to raise an issue with the author of that plugin.
